"""
run_e2e_tests.py imports e2e_config.py in order to get the path to the compiler.
The real e2e_config.py is generated by CMake in the build directory.
This file is a stub intended to make development easier.

THIS IS NOT THE REAL E2E_CONFIG! 
"""
compiled_binary = "" 
test_input_dir = ""